const TEMPLATE = {
    fullFile: `Generated by Thaumcraft Research Editor

import mods.thaumcraft.Research;
import mods.thaumcraft.Warp;

{body}
{localization}`,
    setName: 'Research.setName("{key}", "{name}");',
    setParents: 'Research.setParents("{key}", {parents});',
    setRequiredAspects: 'Research.setAspects("{key}", "{aspects}");',
    addToResearch: 'Warp.addToResearch("{key}", {amount});',
    removeFromResearch: 'Warp.removeFromResearch("{key}");',
    moveResearch: 'Research.moveResearch("{key}", "{tab}", {x}, {y});',
    setComplexity: 'Research.setComplexity("{key}", {complexity});',
    // Options
    setRound: 'Research.setRound("{key}", {value});',
    setSpiky: 'Research.setSpiky("{key}", {value});',
    setStub: 'Research.setStub("{key}", {value});',
    setSecondary: 'Research.setSecondary("{key}", {value});',
    setVirtual: 'Research.setVirtual("{key}", {value});',
    setAutoUnlock: 'Research.setAutoUnlock("{key}", {value});',
    setConcealed: 'Research.setConcealed("{key}", {value});',
    // Pages
    textPage: `Research.addPage("{key}", "tc.research_page.{key}.{pageIndex}");`,
    craftingPage: `Research.addCraftingPage("{key}", <{output}>);`,
    arcanePage: `Research.addArcanePage("{key}", <{output}>);`,
    cruciblePage: `Research.addCruciblePage("{key}", <{output}>);`,
    infusionPage: `Research.addInfusionPage("{key}", <{output}>);`,
    enchantmentPage: `Research.addEnchantmentPage("{key}", {enchantmentId});`,
    refreshResearchRecipe: 'Research.refreshResearchRecipe("{key}");',
    addPrereq: 'Research.addPrereq("{key}", "{parent}", {hidden});',
    addSibling: 'Research.addSibling("{key}", "{sibling}");',
    clearPrereqs: 'Research.clearPrereqs("{key}");',
    clearSiblings: 'Research.clearSiblings("{key}");'
};

function fillTemplate(templateStr, vars) {
    return templateStr.replace(/\{(\w+)\}/g, (m, k) => vars[k] ?? '');
}
