// Templates and helper for generating output script
// Use TEMPLATE and TEMPLATE_ORDER to control output formatting and order.
const TEMPLATE = {
    fullFile: `// Generated by Thaumcraft Research Editor
// https://github.com/Chlorine0808/Thaumcraft-Research-Editor

import mods.thaumcraft.Research;
import mods.thaumcraft.Warp;

{body}
{localization}`,
    // Basics
    setRequiredAspects: 'Research.setAspects("{key}", "{aspects}");',
    addToResearch: 'Warp.addToResearch("{key}", {amount});',
    removeFromResearch: 'Warp.removeFromResearch("{key}");',
    moveResearch: 'Research.moveResearch("{key}", "{tab}", {x}, {y});',
    setComplexity: 'Research.setComplexity("{key}", {complexity});',
    // Options
    setRound: 'Research.setRound("{key}", {value});',
    setSpiky: 'Research.setSpiky("{key}", {value});',
    setStub: 'Research.setStub("{key}", {value});',
    setSecondary: 'Research.setSecondary("{key}", {value});',
    setVirtual: 'Research.setVirtual("{key}", {value});',
    setAutoUnlock: 'Research.setAutoUnlock("{key}", {value});',
    setConcealed: 'Research.setConcealed("{key}", {value});',
    // Prerequisites
    clearPrereqs: 'Research.clearPrereqs("{key}");',
    clearSiblings: 'Research.clearSiblings("{key}");',
    addPrereq: 'Research.addPrereq("{key}", "{parent}", {hidden});',
    addSibling: 'Research.addSibling("{key}", "{sibling}");',
    // Pages
    textPage: `Research.addPage("{key}", "tc.research_page.{key}.{pageIndex}");`,
    craftingPage: `Research.addCraftingPage("{key}", <{output}>);`,
    arcanePage: `Research.addArcanePage("{key}", <{output}>);`,
    cruciblePage: `Research.addCruciblePage("{key}", <{output}>);`,
    infusionPage: `Research.addInfusionPage("{key}", <{output}>);`,
    enchantmentPage: `Research.addEnchantmentPage("{key}", {enchantmentId});`,
    refreshResearchRecipe: 'Research.refreshResearchRecipe("{key}");'
};

function fillTemplate(templateStr, vars) {
    return templateStr.replace(/\{(\w+)\}/g, (m, k) => vars[k] ?? '');
}

// Default output section order. Modify this array to change output order.
window.TEMPLATE_ORDER = ['addResearch', 'move', 'aspects', 'complexity', 'warp', 'prereqs', 'siblings', 'options', 'pages', 'refresh', 'localization'];

// Section comments that will be inserted before the given section when generating output.
// Example: window.TEMPLATE_SECTION_COMMENTS = { options: '\n// --- Options ---\n' };
window.TEMPLATE_SECTION_COMMENTS = window.TEMPLATE_SECTION_COMMENTS || {};
