const TEMPLATE = {
    fullFile: `// Generated by Thaumcraft Research Editor
// https://github.com/Chlorine0808/Thaumcraft-Research-Editor

import mods.thaumcraft.Research;
import mods.thaumcraft.Warp;

{body}
{localization}`,
    // Basics
    setRequiredAspects: 'Research.setAspects("{key}", "{aspects}");',
    addToResearch: 'Warp.addToResearch("{key}", {amount});',
    removeFromResearch: 'Warp.removeFromResearch("{key}");',
    moveResearch: 'Research.moveResearch("{key}", "{tab}", {x}, {y});',
    setComplexity: 'Research.setComplexity("{key}", {complexity});',
    // Options
    setRound: 'Research.setRound("{key}", {value});',
    setSpiky: 'Research.setSpiky("{key}", {value});',
    setStub: 'Research.setStub("{key}", {value});',
    setSecondary: 'Research.setSecondary("{key}", {value});',
    setVirtual: 'Research.setVirtual("{key}", {value});',
    setAutoUnlock: 'Research.setAutoUnlock("{key}", {value});',
    setConcealed: 'Research.setConcealed("{key}", {value});',
    // Prerequisites
    clearPrereqs: 'Research.clearPrereqs("{key}");',
    clearSiblings: 'Research.clearSiblings("{key}");',
    addPrereq: 'Research.addPrereq("{key}", "{parent}", {hidden});',
    addSibling: 'Research.addSibling("{key}", "{sibling}");',
    // Pages
    textPage: `Research.addPage("{key}", "tc.research_page.{key}.{pageIndex}");`,
    craftingPage: `Research.addCraftingPage("{key}", <{output}>);`,
    arcanePage: `Research.addArcanePage("{key}", <{output}>);`,
    cruciblePage: `Research.addCruciblePage("{key}", <{output}>);`,
    infusionPage: `Research.addInfusionPage("{key}", <{output}>);`,
    enchantmentPage: `Research.addEnchantmentPage("{key}", {enchantmentId});`,
    refreshResearchRecipe: 'Research.refreshResearchRecipe("{key}");'
};

function fillTemplate(templateStr, vars) {
    return templateStr.replace(/\{(\w+)\}/g, (m, k) => vars[k] ?? '');
}

// 出力セクションのデフォルト順。必要ならこの配列を書き換えて順序を変更してください。
window.TEMPLATE_ORDER = ['addResearch', 'move', 'aspects', 'complexity', 'warp', 'prereqs', 'siblings', 'options', 'pages', 'refresh', 'localization'];

// セクションごとに、出力時にそのセクションの直前に挿入する文字列（コメントや空行など）を指定できます。
window.TEMPLATE_SECTION_COMMENTS = {
    'addResearch': '\n// Add Research',
    'move': '\n// Move',
    'aspects': '\n// Aspects',
    'complexity': '\n// Complexity',
    'warp': '\n// Warp',
    'prereqs': '\n// Prerequisites',
    'siblings': '\n// Siblings',
    'options': '\n// Options',
    'pages': '\n// Pages',
    'refresh': '\n// Refresh',
    'localization': '\n// Localization'
};
